# Generated by Django 4.0.6 on 2023-03-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_usermodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='phone_number',
            field=models.IntegerField(default='08109137270'),
            preserve_default=False,
        ),
    ]
